export const ACTION_TYPES = {
  AUTHENTICATION_REQUEST: 'AUTHENTICATION_REQUEST',
  AUTHENTICATION_SUCCESS: 'AUTHENTICATION_SUCCESS',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED'
}

export const loginProcess = (username = '', password = '') => ({
  type: ACTION_TYPES.AUTHENTICATION_REQUEST,
  username,
  password
})
